### PR TITLE
Clean up members' expectations

### PR DESCRIPTION
**Pull request by ArcticEcho**
Update graveyard criteria, normalise room owner capitalisation, fix/improve typos/grammar.

### CODE REVIEW

**Comment by gunr2171** [comment]
You really like your commas on bullet points. http://www.businesswritingblog.com/business_writing/2012/01/punctuating-bullet-points-.html

**Comment by ArcticEcho** [comment]
@gunr2171 Style manuals vary I guess. What would you prefer?

**Comment by Tiny-Giant** [comment]
Looks good to me. Will wait for everyone else to review.

**Comment by gunr2171** [comment]
For me, bullets that are a short list of items should not have punctuation.

Make sure you buy:

* Eggs
* Bread
* Water
* Meat

I don't know why, but it really irks me when I see it any other way. Call it OCD.

**Comment by ArcticEcho** [comment]
Alright, I'll update it.

**Pull request merged**
